# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.11                 # https://pyreadiness.org/3.12
  - uv=0.8.17                      # https://github.com/astral-sh/uv
  - pip:
    - robocorp==3.0.0             # https://pypi.org/project/robocorp
    - robocorp-truststore==0.9.1     # https://pypi.org/project/robocorp-truststore/
    - rpaframework-assistant==5.0.0   # https://pypi.org/project/rpaframework-assistant/
    - requests==2.32.5       # https://pypi.org/project/requests
    - gitpython==3.1.45      # https://gitpython.readthedocs.io/en/stable/
    - pandas==2.3.3         # https://pandas.pydata.org/docs/whatsnew/index.html
    - beautifulsoup4==4.12.3 # https://pypi.org/project/beautifulsoup4/
    - jinja2==3.1.6          # https://pypi.org/project/Jinja2/
    - beautifulsoup4==4.14.2 # https://pypi.org/project/beautifulsoup4/