# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.11
  - uv=0.8.17
  - pip:
      - robocorp==3.0.0
      - robocorp-truststore==0.9.1
      - rpaframework-assistant==5.0.0
      - requests==2.32.5
      - gitpython==3.1.45
      - pandas==2.3.3
      - beautifulsoup4==4.14.3
      - jinja2==3.1.6
      - redis==7.1.0
      - psycopg2-binary==2.9.11
      - SQLAlchemy==2.0.45
      - pymongo==4.15.5
      - robocorp_adapters_custom==0.1.3
