[tool.robocorp.log]
log_filter_rules = [
    # Log full information for user code (tasks.py and scripts)
    {name = "tasks", kind = "full_log"},
    {name = "scripts.*", kind = "full_log"},
    
    # Log library calls from user code with minimal overhead
    {name = "robocorp.*", kind = "log_on_project_call"},
    {name = "git", kind = "log_on_project_call"},
    {name = "pathlib", kind = "log_on_project_call"},
    {name = "json", kind = "log_on_project_call"},
    {name = "shutil", kind = "log_on_project_call"},
    {name = "os", kind = "log_on_project_call"},
    
    # Exclude noisy internal modules
    {name = "urllib3.*", kind = "exclude"},
    {name = "requests.*", kind = "exclude"},
]

# By default, exclude other library modules to reduce log noise
default_library_filter_kind = "exclude"
