apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fetch-repos-gha-runner-scale-set          # Logical app name in Argo CD UI
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'oci://ghcr.io/actions/actions-runner-controller-charts'
    chart: gha-runner-scale-set
    targetRevision: 0.12.0 # Adjust version as needed
    helm:
      valueFiles:
      - $values/repos/fetch-repos/values.yaml
  - repoURL: 'https://github.com/joshyorko/fetch-repos-bot.git'
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true