runnerScaleSetName: fetch-repos-bot-runner-k8s-kaniko

githubConfigUrl: https://github.com/joshyorko/fetch-repos-bot
githubConfigSecret: pre-defined-secret     # PAT or GitHub App for runner registration

containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    storageClassName: local-path
    accessModes: ["ReadWriteOnce"]
    resources:
      requests: { storage: 5Gi }

template:
  spec:
    # let Kaniko write its own auth file, no extra volumes needed
    imagePullSecrets: [{ name: ghcr-login }]
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"   # lets you mix shell + container steps
