# --------------------------------------------------------------------
# GitHub configuration
# --------------------------------------------------------------------
githubConfigUrl: "https://github.com/joshyorko/fetch-repos-bot"  # Replace with your GitHub URL

githubConfigSecret: pre-defined-secret

# --------------------------------------------------------------------
# Runner scale set configuration
# --------------------------------------------------------------------
runnerScaleSetName: "fetch-repos-bot-runner-k8s"  # Name of the runner scale set


# --------------------------------------------------------------------
# Runner Pod template configuration
# --------------------------------------------------------------------
template:
  spec:
    dnsPolicy: None
    dnsConfig:
      nameservers: ["8.8.8.8", "1.1.1.1"]
    #imagePullSecrets:        # omit this block if your image is public
    #  - name: ghcr-login
    containers:
      - name: runner
        image: ghcr.io/joshyorko/fetch-repos-bot-runner:main-484fb43 # Replace with your image
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
maxRunners: 5
minRunners: 0
