name: Build and Push Fetch Repos Bot Runner Docker Image

on:
  push:
    paths:
      - 'robot.yaml'
      - 'conda.yaml'
      - 'arc-docker/**'
  pull_request:
    paths:
      - 'robot.yaml'
      - 'conda.yaml'
      - 'arc-docker/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/fetch-repos-bot-runner

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Copy configuration files to arc-docker directory
        run: |
          cp robot.yaml arc-docker/
          cp conda.yaml arc-docker/

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./arc-docker
          file: ./arc-docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clean up copied files
        run: |
          rm -f arc-docker/robot.yaml arc-docker/conda.yaml

      - name: Update image tag in values.yaml and GitHub Actions workflows
        uses: mikefarah/yq@v4.45.4
        with:
          cmd: |
            NEW_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -oE '[^, ]+$')
            echo "Updating arc-docker/values.yaml to use tag $NEW_TAG"
            yq -i '.template.spec.containers[0].image |= sub("ghcr.io/joshyorko/fetch-repos-bot-runner:[^\"']*", "ghcr.io/joshyorko/fetch-repos-bot-runner:" + strenv(NEW_TAG))' arc-docker/values.yaml
            echo "Updating .github/workflows/fetch-repos-matrix-hosted.yaml to use tag $NEW_TAG"
            yq -i '(.jobs.producer.container.image // .jobs.consumer.container.image) |= sub("ghcr.io/joshyorko/fetch-repos-bot-runner:[^\"']*", "ghcr.io/joshyorko/fetch-repos-bot-runner:" + strenv(NEW_TAG))' .github/workflows/fetch-repos-matrix-hosted.yaml
            echo "Updating .github/workflows/fetch-repos-matrix-self-hosted.yaml to use tag $NEW_TAG"
            yq -i '(.jobs.producer.container.image // .jobs.consumer.container.image) |= sub("ghcr.io/joshyorko/fetch-repos-bot-runner:[^\"']*", "ghcr.io/joshyorko/fetch-repos-bot-runner:" + strenv(NEW_TAG))' .github/workflows/fetch-repos-matrix-self-hosted.yaml

      - name: Commit and push updated image tags
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update runner image tag in values.yaml and workflows"
          file_pattern: |
            arc-docker/values.yaml
            .github/workflows/fetch-repos-matrix-hosted.yaml
            .github/workflows/fetch-repos-matrix-self-hosted.yaml
