name: Cache RCC/Robocorp Home

on:
  workflow_dispatch: 


jobs:
  cache-robocorp-home:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup RCC (if needed)
        run: |
          if ! command -v rcc &> /dev/null; then
            curl -Ls -o rcc https://github.com/joshyorko/rcc/releases/download/v18.8.0/rcc-linux64
            chmod a+x rcc
            sudo mv rcc /usr/local/bin/
          fi
          rcc --version

      - name: Disable RCC telemetry
        run: rcc config identity -t

      - name: Prime RCC environment cache
        run: |
          # Resolve the conda environment once to populate caches
          rcc holotree variables
          rcc holotree pull -f robot.yaml || true
          # Dry-run to ensure env is created
          rcc run -t Producer -e devdata/env-for-producer.json || true

      - name: Cache Python and RCC dirs
        uses: actions/cache@v4
        with:
          path: |
            ~/.robocorp
            ~/.cache/robocorp
            ~/.cache/pip
          key: ${{ runner.os }}-robocorp-${{ hashFiles('conda.yaml', 'robot.yaml') }}
          restore-keys: |
            ${{ runner.os }}-robocorp-
