name: Fetch Robocorp Repositories and zip them

on:
  workflow_dispatch:

jobs:
  fetch-robocorp:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download RCC
        run: |
          chmod +x start.sh

      - name: Run robot
        run: |
          ./start.sh

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: robocorp-repositories
          path: output/results.zip
