name: Fetch Robocorp Repositories and zip them

on:
  workflow_dispatch:

jobs:
  fetch-robocorp:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Make start.sh executable
        run: |
          chmod +x start.sh;

      - name: Run start.sh
        run: ./start.sh

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: robocorp-repositories
          path: output/repos.zip

      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf output/*
    
