name: Robocorp ARC Single-Job Workflow

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: arc-runner-myrepo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Ensure RCC is installed
        run: |
          if ! command -v rcc &> /dev/null; then
            echo "RCC not found. Downloading..."
            curl -o rcc https://downloads.robocorp.com/rcc/releases/latest/linux64/rcc
            chmod +x rcc
            sudo mv rcc /usr/local/bin/
          else
            echo "RCC is already installed."
          fi

      - name: Make start.sh executable
        run: chmod +x start.sh

      - name: Run start.sh
        run: ./start.sh

      - name: Upload output directory
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
