name: RCC Holotree Vars on Specific Runners

on:
  workflow_dispatch:

jobs:
  holotree-vars:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - arc-runner-k8s-4gf7b-runner-2cdrf
          - arc-runner-k8s-4gf7b-runner-bcmm4
          - arc-runner-k8s-4gf7b-runner-jzw7z
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Ensure RCC is installed
        run: |
          if ! command -v rcc &> /dev/null; then
            echo "RCC not found. Downloading..."
            curl -o rcc https://downloads.robocorp.com/rcc/releases/latest/linux64/rcc
            chmod +x rcc
            sudo mv rcc /usr/local/bin/
          else
            echo "RCC is already installed."
          fi

      - name: Disable RCC telemetry
        run: |
          echo "Disabling RCC telemetry..."
          rcc config identity -t

      - name: Run rcc holotree vars
        run: rcc holotree vars
